name: Exemple cicd
on:
    push:
        branches: [main]

jobs:
    job1:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_PASSWORD: postgres
                ports:
                    - 5432:5432


        steps:
            - name: step 1
              run: echo "Hello world !!"
            - name: step 2
              uses: actions/checkout@v7
            - name: step 3
              run: docker ps -a
            